spring:
  application:
    name: eMall-third-party

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-us-west-1.aliyuncs.com
        bucket: emall-rongjian
      access-key: LTAI5tQHkVE62vdbAHzhyWnH
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5

server:
  port: 30000